name: flutter_design_system_template
description: Token based Flutter design system
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
